package ch.fhnw.cpib.compiler.scanner.enums;

public enum Terminals {
	  LPAREN("LPAREN"), RPAREN("RPAREN"), LBRACE("LBRACE"), RBRACE("RBRACE"),
	  COMMA("COMMA"), SEMICOLON("SEMICOLON"), COLON("COLON"), DOTOPR("DOTOPR"),
	  DEBUGIN("DEBUGIN"), DEBUGOUT("DEBUGOUT"), BECOMES("BECOMES"),
	  MULTOPR("MULTOPR"), ADDOPR("ADDOPR"), RELOPR("RELOPR"), BOOLOPR("BOOLOPR"),
	  LITERAL("LITERAL"), IDENT("IDENT"),
	  PROGRAM("PROGRAM"), RECORD("RECORD"), TYPE("TYPE"), CALL("CALL"), NOT("NOT"),
	  IF("IF"), ELSE("ELSE"), ENDIF("ENDIF"),
	  FLOWMODE("FLOWMODE"), CHANGEMODE("CHANGEMODE"), MECHMODE("MECHMODE"),
	  FUN("FUN"), GLOBAL("GLOBAL"), LOCAL("LOCAL"), INIT("INIT"),
	  PROC("PROC"), RETURNS("RETURNS"), SKIP("SKIP"), THEN("THEN"),
	  WHILE("WHILE"), DO("DO"), ENDWHILE("ENDWHILE"), ENDPROGRAM("ENDPROGRAM"),
	  ENDFUN("ENDFUN"),ENDPROC("ENDPROC"),SENTINEL("SENTINEL");
	
	Terminals(String toString) {
		this.toString = toString;
	}
	
	private String toString;
	
	@Override
	public String toString() {
		return toString;
	}
}
